// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/birthday-surprise/BirthdaySurprisePolished.tsx": () => import("../components/mockups/birthday-surprise/BirthdaySurprisePolished.tsx")
};
